--- #YAML:1.0
name:                Text-NSP
version:             1.07
abstract:            Count and identify significant collocations and Ngrams in text
license:             gpl
author:              
    - Ted Pedersen <tpederse at d.umn.edu>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
